AWSTemplateFormatVersion: '2010-09-09'
Description: 'tripsapi

  Rest API to manage Trips

  '
Globals:
  Function:
    MemorySize: 512
    Timeout: 20
Outputs:
  CreateTripRecordFunction:
    Description: CreateTripRecord Lambda Function ARN
    Value:
      Fn::GetAtt:
      - CreateTripRecordFunction
      - Arn
  GetTripRecordsByCityFunction:
    Description: GetTripRecordsByCity Lambda Function ARN
    Value:
      Fn::GetAtt:
      - GetTripRecordsByCityFunction
      - Arn
  GetTriRecordsByCountryFunction:
    Description: GetTriRecordsByCountry Lambda Function ARN
    Value:
      Fn::GetAtt:
      - GetTriRecordsByCountryFunction
      - Arn
  GetTripRecordsByPeriodFunction:
    Description: GetTripRecordsByPeriod Lambda Function ARN
    Value:
      Fn::GetAtt:
      - GetTripRecordsByPeriodFunction
      - Arn
Resources:
  CreateTripRecordFunction:
    Properties:
      CodeUri: s3://aws-sam-fiap-deployt/896a140ec24d1c84f917b82d6bdddd3f
      Events:
        CreateStudyRecord:
          Properties:
            Method: post
            Path: /trips
          Type: Api
      Handler: br.com.tripsapi.handler.CreateTripRecord::handleRequest
      Runtime: java8
    Type: AWS::Serverless::Function
  GetTripRecordsByPeriodFunction:
    Properties:
      CodeUri: s3://aws-sam-fiap-deployt/896a140ec24d1c84f917b82d6bdddd3f
      Events:
        GetStudyRecordsByIsConsumed:
          Properties:
            Method: get
            Path: /trips?start={starts}&end={ends}
            RequestParameters:
            - method.request.querystring.starts
            - method.request.querystring.ends
          Type: Api
      Handler: br.com.tripsapi.handler.GetTripRecordsByPeriod::handleRequest
      Runtime: java8
    Type: AWS::Serverless::Function
  GetTripRecordsByCityFunction:
    Properties:
      CodeUri: s3://aws-sam-fiap-deployt/896a140ec24d1c84f917b82d6bdddd3f
      Events:
        GetTripRecordsByCityFunction:
          Properties:
            Method: get
            Path: /trips/{Country}/?city={City}
            RequestParameters:
            - method.request.querystring.Country
            - method.request.querystring.City
          Type: Api
      Handler: br.com.tripsapi.handler.GetTripRecordsByCity::handleRequest
      Runtime: java8
    Type: AWS::Serverless::Function
  GetTriRecordsByCountryFunction:
    Properties:
      CodeUri: s3://aws-sam-fiap-deployt/896a140ec24d1c84f917b82d6bdddd3f
      Events:
        GetStudyRecordsByTag:
          Properties:
            Method: get
            Path: /trips/{Country}
            RequestParameters:
            - method.request.querystring.Country
          Type: Api
      Handler: br.com.tripsapi.handler.GetTripRecordsByCountry::handleRequest
      Runtime: java8
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
